        <footer class="navbar-default navbar-fixed-bottom footer">
            <div class="row vertical-center">
                <div class="col-xs-3">
                    <a href="http://validator.w3.org/check?uri=referer;ss=1" style="margin-left: 15px;">
                        <img src="https://www.w3.org/html/logo/badge/html5-badge-h-css3-semantics.png" width="98px" height="38px" alt="HTML5 Powered with CSS3 / Styling, and Semantics" title="HTML5 Powered with CSS3 / Styling, and Semantics">
                    </a>
                </div>
                <div class="col-xs-6">
                    <center>
                        <span class="text-muted">Proudly created and maintained by the Ducky-Mc-Duckerson team</span>
                    </center>
                </div>
            </div>
        </footer>