            <div class="row">
                <div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
                    <div class="panel panel-default">
                        <div class="panel-heading">Ducky Mc Duckerson Web UI</div>
                        <div class="panel-body">
                            <p>HY! :D</p>
                        </div>
                    </div>
                </div>
            </div>