        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/home">Ducky Mc Duckerson</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li role="presentation"<?=($PageID == 0 ? " class=\"active\"" : "");?>>
                            <a href="/home" title="Home">
                                <span class="glyphicon glyphicon-home"></span>
                            </a>
                        </li>
                        <li role="presentation">
                            Item 2
                        </li>
                        <li role="presentation">
                            Item 3
                        </li>
                        <li role="presentation">
                            Item 4
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-menu-hamburger"></span>&nbsp;&nbsp;<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li role="presentation">
                                    Item 1
                                </li>
                                <li role="separator" class="divider"></li>
                                <li role="presentation">
                                    Item 2
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>